/* GENERATED by BACKEND_ADMIN_ONLY_RESTORE.js — safe to edit, but read the
   reasoning in that file first.

   Restoring from the Recycle Bin writes rows back into live tables. It is an
   administrator action, and the frontend hiding the button is not enforcement.

   THE ROLE IS READ FROM THE DATABASE, NOT FROM THE TOKEN. Trusting a role
   claim in a JWT means anyone who can mint or alter a token grants themselves
   restore, and it fails in the direction of ALLOWING when the token shape
   changes. The identifier comes from the token; the role is looked up fresh,
   so a revoked admin loses restore immediately rather than at token expiry.

   IT FAILS CLOSED. No identifiable caller, no matching row, or a query that
   throws — all deny. */
const pool = require('./db');

const ADMIN_ROLES = ['admin', 'administrator', 'root', 'superadmin', 'super admin', 'super_admin'];

const LOOKUP = "SELECT u.role::text AS role, false AS admin_flag FROM ip_manager_users u WHERE u.id::text = $1 OR lower(u.username::text) = lower($1) LIMIT 1";

async function requireAdmin(req, res, next) {
  const u = req.user || {};
  /* Every field a token in this codebase has been seen to carry. The first
     one present wins; the lookup matches it against id OR username. */
  const ident = u.id ?? u.user_id ?? u.uuid ?? u.username ?? u.user_name ?? u.sub ?? u.email;

  if (ident === undefined || ident === null || String(ident).trim() === '') {
    return res.status(401).json({ ok: false, error: 'Not signed in.' });
  }

  try {
    const { rows } = await pool.query(LOOKUP, [String(ident)]);
    const row = rows[0];
    if (row === undefined) {
      console.warn('[archive] restore denied: no user row for ' + String(ident));
      return res.status(403).json({ ok: false, error: 'Restoring is limited to administrators.' });
    }

    const ok = row.admin_flag === true
      || ADMIN_ROLES.indexOf(String(row.role || '').trim().toLowerCase()) >= 0;

    if (ok !== true) {
      console.warn('[archive] restore denied for ' + String(ident) + ' (role "' + row.role + '")');
      return res.status(403).json({ ok: false, error: 'Restoring is limited to administrators.' });
    }

    return next();
  } catch (err) {
    /* A guard that opens when it cannot decide is not a guard. */
    console.error('[archive] restore guard could not resolve the caller:', err.message);
    return res.status(403).json({ ok: false, error: 'Could not verify your permissions.' });
  }
}

module.exports = requireAdmin;
